apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-repo
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/evans22j/Budget-App.git

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
    - name: url
      value: index.docker.io/thulasiramteja/sample-project/telkon-repoS
